// scripts/copy-seed.mjs — reads the demo story, writes it as a TS constant
// so the editor's seed and the story file can never drift.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const storyPath = resolve(root, "..", "..", "stories", "العطر_المفقود.qalam");
const outDir = resolve(root, "src", "generated");
const outPath = resolve(outDir, "seed-story.ts");

if (!existsSync(storyPath)) {
  console.error("Seed story not found at:", storyPath);
  process.exit(1);
}

const raw = readFileSync(storyPath, "utf-8");
// Escape backticks and backslashes for the template literal
const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`");

const ts = `// Generated by scripts/copy-seed.mjs — do not edit.
// Reads stories/العطر_المفقود.qalam at build time.

export const SEED_STORY = \`${escaped}\`;
`;

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, ts, "utf-8");
console.log(`[copy-seed] Wrote ${outPath} (${raw.length} chars)`);
