// scripts/copy-seed.mjs — reads the editor's example story, writes it as a TS
// constant so the seed and the story file can never drift.
//
// This used to read stories/العطر_المفقود.qalam. That story uses multi-branch
// conditionals and `{المكوّنات}` interpolation — both valid, neither with a
// field in the visual writer — so "افتح مثالًا" threw the writer out of the
// pane and into a fallback banner. An example that ejects you from the editor
// is not an example. العطر المفقود is still the landing page's demo, still the
// exported story, and still the regression case; it is simply not what the
// editor offers a beginner.
//
// The invariant this script now carries: THE SEED MUST OPEN IN THE VISUAL
// WRITER. `packages/editor/tests/writer.spec.ts` asserts it by importing it.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const storyPath = resolve(root, "..", "..", "stories", "طائرة_الورق.qalam");
const outDir = resolve(root, "src", "generated");
const outPath = resolve(outDir, "seed-story.ts");

if (!existsSync(storyPath)) {
  console.error("Seed story not found at:", storyPath);
  process.exit(1);
}

const raw = readFileSync(storyPath, "utf-8");
// Escape backticks and backslashes for the template literal
const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`");

const ts = `// Generated by scripts/copy-seed.mjs — do not edit.
// Reads stories/طائرة_الورق.qalam at build time.

export const SEED_STORY = \`${escaped}\`;
`;

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, ts, "utf-8");
console.log(`[copy-seed] Wrote ${outPath} (${raw.length} chars)`);
