// ---------------------------------------------------------------------------
// copy-runtime.mjs — reads the built runtime bundle + dark theme CSS and
// writes them as TypeScript constants so the browser export can inline them.
//
// Run AFTER `npm run build -w @aqlamna/runtime`.
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const runtimeDist = join(root, "..", "runtime", "dist", "aqlamna-runtime.js");
const darkCss = join(root, "..", "runtime", "src", "themes", "dark.css");
const outDir = join(root, "src", "generated");
const outFile = join(outDir, "runtime-bundle.ts");

mkdirSync(outDir, { recursive: true });

const runtimeJs = readFileSync(runtimeDist, "utf-8");
const css = readFileSync(darkCss, "utf-8");

const content = [
  "// Auto-generated by scripts/copy-runtime.mjs — do not edit",
  "// Regenerate with: node scripts/copy-runtime.mjs",
  "",
  "export const RUNTIME_BUNDLE = " + JSON.stringify(runtimeJs) + ";",
  "",
  "export const DARK_THEME_CSS = " + JSON.stringify(css) + ";",
  "",
].join("\n");

writeFileSync(outFile, content, "utf-8");
console.log(
  "[copy-runtime] Wrote %s (%d bytes, runtime: %d, css: %d)",
  outFile,
  content.length,
  runtimeJs.length,
  css.length,
);
