// scripts/copy-seed.mjs — reads the editor's example story, writes it as a TS
// constant so the seed and the story file can never drift.
//
// This used to read stories/العطر_المفقود.qalam. That story uses multi-branch
// conditionals and `{المكوّنات}` interpolation — both valid, neither with a
// field in the visual writer — so "افتح مثالًا" threw the writer out of the
// pane and into a fallback banner. An example that ejects you from the editor
// is not an example. العطر المفقود is still the landing page's demo, still the
// exported story, and still the regression case; it is simply not what the
// editor offers a beginner.
//
// The invariant this script now carries: THE SEED MUST OPEN IN THE VISUAL
// WRITER. `packages/editor/tests/writer.spec.ts` asserts it by importing it.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const storyPath = resolve(root, "..", "..", "stories", "طائرة_الورق.qalam");
const outDir = resolve(root, "src", "generated");
const outPath = resolve(outDir, "seed-story.ts");

if (!existsSync(storyPath)) {
  console.error("Seed story not found at:", storyPath);
  process.exit(1);
}

const raw = readFileSync(storyPath, "utf-8");
// Escape backticks and backslashes for the template literal
const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`");

// The example declares an image, and a first-time visitor has an empty
// IndexedDB — so without the bytes the story opens on a placeholder frame and
// the one feature it exists to demonstrate is invisible. These WebPs are real
// pipeline output (768px long side, the same downscale image-db.ts performs in
// the browser), not hand-made assets. To change one, draw it in the editor and
// replace the file; never touch the base64 in the generated module.
const imagesDir = resolve(root, "..", "..", "stories", "images");
const seedImages = {};
if (existsSync(imagesDir)) {
  for (const file of readdirSync(imagesDir)) {
    const m = /^طائرة_الورق-(.+)\.webp$/.exec(file);
    if (!m) continue;
    const b64 = readFileSync(resolve(imagesDir, file)).toString("base64");
    seedImages[m[1]] = `data:image/webp;base64,${b64}`;
  }
}

// A declared image with no bytes here would ship a broken example quietly.
const declared = [...raw.matchAll(/^صورة\s+(\S+)\s*=/gm)].map((m) => m[1]);
for (const name of declared) {
  if (!(name in seedImages)) {
    console.error(
      `[copy-seed] the example declares the image "${name}" but ` +
        `stories/images/طائرة_الورق-${name}.webp does not exist.`,
    );
    process.exit(1);
  }
}

const ts = `// Generated by scripts/copy-seed.mjs — do not edit.
// Reads stories/طائرة_الورق.qalam and stories/images/*.webp at build time.

export const SEED_STORY = \`${escaped}\`;

/** Image name → WebP data URL, seeded into IndexedDB when the example loads. */
export const SEED_IMAGES: Record<string, string> = ${JSON.stringify(seedImages, null, 2)};
`;

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, ts, "utf-8");
const imageBytes = Object.values(seedImages).reduce((n, d) => n + d.length, 0);
console.log(
  `[copy-seed] Wrote ${outPath} (${raw.length} chars, ` +
    `${Object.keys(seedImages).length} image(s), ${Math.round(imageBytes / 1024)}KB base64)`,
);
