// ---------------------------------------------------------------------------
// copy-runtime.mjs — reads the built runtime bundle + all theme CSS files and
// writes them as TypeScript constants so the browser export can inline them.
//
// Run AFTER `npm run build -w @aqlamna/runtime`.
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const runtimeDist = join(root, "..", "runtime", "dist", "aqlamna-runtime.js");
const themesDir = join(root, "..", "runtime", "src", "themes");
const outDir = join(root, "src", "generated");
const outFile = join(outDir, "runtime-bundle.ts");

mkdirSync(outDir, { recursive: true });

const runtimeJs = readFileSync(runtimeDist, "utf-8");

function readTheme(name) {
  return readFileSync(join(themesDir, `${name}.css`), "utf-8");
}

const darkCss  = readTheme("dark");
const lightCss = readTheme("light");
const bookCss  = readTheme("book");

const content = [
  "// Auto-generated by scripts/copy-runtime.mjs — do not edit",
  "// Regenerate with: node scripts/copy-runtime.mjs",
  "",
  "export const RUNTIME_BUNDLE = " + JSON.stringify(runtimeJs) + ";",
  "",
  "export const DARK_THEME_CSS  = " + JSON.stringify(darkCss)  + ";",
  "export const LIGHT_THEME_CSS = " + JSON.stringify(lightCss) + ";",
  "export const BOOK_THEME_CSS  = " + JSON.stringify(bookCss)  + ";",
  "",
].join("\n");

writeFileSync(outFile, content, "utf-8");
console.log(
  "[copy-runtime] Wrote %s (%d bytes, runtime: %d, dark: %d, light: %d, book: %d)",
  outFile,
  content.length,
  runtimeJs.length,
  darkCss.length,
  lightCss.length,
  bookCss.length,
);
